### ISSUE TITLE
For llnl-scraper config, assign organization based on orgs

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/cyhy_amis#279]
# 🚀 Feature Proposal

The [llnl-scraper config](https://github.com/cisagov/cyhy_amis/blob/develop/ansible/roles/code_gov_update/tasks/main.yml#L21-L46) should tailor the `organization` field to the long name of the owner of the `orgs` instead of defaulting to "Department of Homeland Security", which is already represented in `"agency": "DHS"`.

For the three orgs represented in the code:
* `cisagov` would be "Cybersecurity and Infrastructure Security Agency"
* `US-CBP` would be "U.S. Customs and Border Protection"
* `usdhs` would be "Department of Homeland Security" – and could possibly be removed at this point, since it no longer appears active (all repos are archived).

This could perhaps be achieved by variablizing the `organization` field, or maybe by running the scraper multiple times and concatenating the results.

## Motivation

It'd be useful for CISA to be better represented in code.gov. For example, a [search for COOL-related stuff at code.gov](https://code.gov/search?&page=1&query=cool&size=10&sort=best_match) shows DHS, not CISA, and that's not (as) cool.

(cc: @mcdonnnj)

**Comment by mcdonnnj** [comment]
So I looked at the [configuration options](https://github.com/LLNL/scraper#config-file-options) for [LLNL/scraper](https://github.com/LLNL/scraper) and our [Docker image](https://github.com/cisagov/code-gov-update). I believe it will require changes here and in [cisagov/code-gov-update](https://github.com/cisagov/code-gov-update) to support breaking up by organization instead of everything being lumped generically under `DHS - Department of Homeland Security`.

Specifically the `docker-compose` [configuration](https://github.com/cisagov/code-gov-update/blob/develop/docker-compose.yml) is built around a single configuration JSON. The `LLNL` configuration setup only takes one `agency` and one `organization`, so we will likely need to template and/or do multiple JSONs.

**Comment by jsf9k** [comment]
Thanks to @h-m-f-t for noticing this and to @mcdonnnj for looking into it.  This seems quite doable, but it will probably be a week or so before I can get to it.  I've got a COOL issue that is pressing down on me with the weight of 10,000 suns, so I need to get that resolved first.

If we _do not_ define an organization in the LLNL scraper configuration then I _think_ the scraper will just grab the organization's long name for each repo, as it is defined in GitHub (see [here](https://github.com/LLNL/scraper/blob/master/scraper/code_gov/__init__.py#L161-L163), [here](https://github.com/LLNL/scraper/blob/master/scraper/code_gov/__init__.py#L34), [here](https://github.com/LLNL/scraper/blob/master/scraper/code_gov/models.py#L231-L239), and [here](https://github.com/LLNL/scraper/blob/master/scraper/gen_code_gov_json.py#L140-L142)).  This would give exactly the results @h-m-f-t mentioned above except in the case of the `usdhs` organization, which @h-m-f-t said we could probably just remove anyway.  (Their long name is "U.S. Department of Homeland Security".)  If I'm right then this is a simple change.

If you're able to get to this before me @mcdonnnj then by all means go ahead.

Because I can never remember the exact URL, I will go ahead and include [this link](https://www.dhs.gov/code.json) for my own benefit.

**Comment by jsf9k** [comment]
Note that in cisagov/cyhy_amis#280 we decided to leave the `us-dhs` GitHub organization in the scraper configuration after all.  @mcdonnnj pointed out that archived repositories in our `cisagov` organization get included in the code.gov JSON, so an organization being comprised entirely of archived repositories is not a sufficient condition for removal.

The "long name" of the `us-dhs` repo does not exactly correspond with what @h-m-f-t mentioned above, but the easiest solution there is to ask @brodygov to change the organization name from "U.S. Department of Homeland Security" to "Department of Homeland Security".
