### ISSUE TITLE
Add ClamAV to CyHy AMIs

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cyhy_amis#313]
# 🚀 Feature Proposal #

Add ClamAV to the CyHy AMIs via [cisagov/ansible-role-clamav](https://github.com/cisagov/ansible-role-clamav).

## Motivation ##

The security folks have been asking for this, and it's an easy thing for us to do for them.

**Comment by mcdonnnj** [comment]
As an update, I discovered that I inadvertently broke [cisagov/ansible-role-cyhy-archive](https://github.com/cisagov/ansible-role-cyhy-archive) with https://github.com/cisagov/ansible-role-cyhy-core/pull/28. Since I need to update [cisagov/ansible-role-cyhy-archive](https://github.com/cisagov/ansible-role-cyhy-archive) to deal with the changes in [cisagov/ansible-role-cyhy-core](https://github.com/cisagov/ansible-role-cyhy-core), I am skeletonizing the repository as part of the process.
