### ISSUE TITLE
Mongo provisioner not able to locate `pymongo` module

### ISSUE THREAD

**Issue by dav3r** [cisagov/cyhy_amis#599]
# 🐛 Bug Report #

When using the [`maintenance/redeployments` branch](https://github.com/cisagov/cyhy_amis/tree/maintenance/redeployments), the Mongo provisioner fails with the error below.

With help from @mcdonnnj, I was able to fix this issue locally by forcing `pymongo 3.6.0` to be installed with `pip3`, rather than [with `pip2`](https://github.com/cisagov/cyhy_amis/blob/d00c00f4d637fcb83861cab546bf67d65fd5385e/ansible/roles/mongo/tasks/main.yml#L14):

```
- name: Install pymongo 3.6
  ansible.builtin.pip:
    executable: /usr/bin/pip3
    name: pymongo
    version: '3.6'
```

## To Reproduce ##

- Use the `maintenance/redeployments` branch
- `terraform apply`

## Expected behavior ##

All ansible provisioners should run without failure.

## Any helpful log output ##

```bash
│ TASK [mongo : Create admin user in admin db (first user, no authentication)] ***
│ An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'pymongo'
│ fatal: [10.10.10.110]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (pymongo) on database1's Python /usr/bin/python3. Please read the module documentation and install
│ it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

**Comment by mcdonnnj** [comment]
I believe this was fully resolved in https://github.com/cisagov/cyhy_amis/pull/642 and that the source of this was that @dav3r was using a development branch which included updates to the Debian versions used for AMIs (merged in #641). These version updates (as well as updated logic in Ansible) resulted in Ansible using Python 3 by default instead of Python 2 for the post-deployment Ansible provisioner.
